services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: facturaProject
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: bash -c "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 facturaProject.wsgi:application"
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:1234@db/facturaProject
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
