# Generated by Django 5.1 on 2024-08-12 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_unidadmedida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unidadMedida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.unidadmedida'),
        ),
    ]
