# Generated by Django 5.1 on 2024-08-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_alter_item_unidadmedida'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPrecio',
            fields=[
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'tipo_precio',
            },
        ),
    ]
