# Generated by Django 5.1 on 2024-08-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_alter_item_tipoprecio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='comprobanteitem',
            name='cantidad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
