# Generated by Django 5.1 on 2024-08-12 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0006_remove_item_cantidad_comprobanteitem_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='valorBajoImpuestos',
        ),
    ]
