# Generated by Django 5.1 on 2024-08-12 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0007_remove_item_valorbajoimpuestos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimpuesto',
            name='impuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.catalogo05tipostributos'),
        ),
        migrations.DeleteModel(
            name='Impuesto',
        ),
    ]
