# Generated by Django 5.1 on 2024-08-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0008_alter_itemimpuesto_impuesto_delete_impuesto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogo05tipostributos',
            old_name='name',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='itemimpuesto',
            name='valorGravado',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
