# Generated by Django 5.1 on 2024-08-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0010_delete_tipocomprobante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo07TiposDeAfectacionDelIGV',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=2, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=200)),
            ],
        ),
    ]
