# Generated by Django 5.1 on 2024-08-15 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0011_catalogo07tiposdeafectaciondeligv'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamiliaProducto',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'familia_producto',
            },
        ),
        migrations.CreateModel(
            name='SegmentoProducto',
            fields=[
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'segmento_producto',
            },
        ),
        migrations.CreateModel(
            name='ClaseProducto',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='facturacion.familiaproducto')),
            ],
            options={
                'db_table': 'clase_producto',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='facturacion.claseproducto')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.AddField(
            model_name='familiaproducto',
            name='segmento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='facturacion.segmentoproducto'),
        ),
    ]
