# Generated by Django 5.1 on 2024-08-15 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0013_alter_claseproducto_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='codigoProducto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='facturacion.producto'),
        ),
    ]
