# Generated by Django 5.1 on 2024-08-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0014_item_codigoproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo51TipoDeOperacion',
            fields=[
                ('codigo', models.CharField(db_column='codigo', max_length=4, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('comprobantes', models.CharField(choices=[('a', 'Option A'), ('b', 'Option B')], max_length=1)),
            ],
        ),
    ]
