# Generated by Django 5.1 on 2024-08-22 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0015_catalogo51tipodeoperacion'),
    ]

    operations = [
    ]
